import QtQuick
import QtQuick.Controls
import Quickshell
import Quickshell.Io
import Quickshell.Wayland
import Quickshell.Hyprland
import Quickshell.Widgets
import "../common"

// Fullscreen, transparent layer-shell overlay holding a card with two tabs:
//   • Shortcuts — a "cheat sheet" listing every keybind (hand-maintained).
//   • Settings  — toggles for shell/system behaviour (keep the laptop awake
//     when the lid is shut, auto-lock on idle).
// Centred on the focused monitor; click the scrim or press Esc to dismiss.
// Same proven scrim pattern as the launcher / control popup (a
// HyprlandFocusGrab races the map and often misses).
//
// Opened/closed over IPC:
//   qs ipc call shortcuts toggle     → Shortcuts tab (Super+/)
//   qs ipc call shortcuts settings   → Settings tab  (Super+Shift+/)
//
// The bind list below is hand-maintained — if you add/rename a bind in
// hyprland.conf, update the matching row here so the sheet stays honest.
PanelWindow {
    id: root

    property bool open: false
    property bool closing: false        // keep mapped through the close fade
    property int tab: 0                  // 0 = Shortcuts, 1 = Settings, 2 = Marketplace
    readonly property int tabCount: 3
    property int settingsRow: 0          // cursor within the Settings tab
    readonly property int settingsCount: 2 + themeSlots.length

    // ── marketplace ─────────────────────────────────────────────────────
    // Browse + download themes straight from the author's GitHub. The source
    // is PINNED (no third-party URLs): installing a theme runs its QML in the
    // shell, so the trust boundary is "you already trust world80's author".
    // The catalog (index.json) is generated by themes/build-catalog.sh; each
    // theme's file list drives a plain curl-per-file into ~/.config/themes/.
    readonly property string mktRepo: "AidanMercer/themes"
    readonly property string mktBranch: "master"
    readonly property string mktRawBase: "https://raw.githubusercontent.com/" + mktRepo + "/" + mktBranch + "/"
    readonly property string mktHome: Quickshell.env("HOME") || ""
    readonly property string mktCacheDir: (Quickshell.env("XDG_CACHE_HOME") || (mktHome + "/.cache")) + "/hypr-marketplace"
    readonly property string mktScript: mktHome + "/.config/quickshell/scripts/theme-install.sh"
    property var mktThemes: []
    property string mktCommit: ""
    property bool mktLoading: false
    property string mktError: ""
    property var mktInstalled: ({})     // name -> true (dirs present in ~/.config/themes)
    property var mktProgress: ({})      // name -> {done,total} while downloading
    property string mktBusy: ""         // the one theme downloading right now
    property int mktRow: 0              // keyboard cursor within the store list
    property string mktArmedRemove: ""  // theme name whose removal is armed (confirm)

    // ── self-update ─────────────────────────────────────────────────────
    // the engine is a git clone at ~/dotfiles; check if it's behind the remote
    // and offer a ff-only pull. checked when the Settings tab opens.
    readonly property string updRepo: mktHome + "/dotfiles"
    property string updState: "idle"    // idle|checking|uptodate|behind|offline|pulling|done|error
    property int updBehind: 0
    property string updLocal: ""        // "abc1234 (3 days ago)"
    property int updNotifiedBehind: 0   // how many commits we last notified about (no spam)

    // ── per-theme widget toggles ────────────────────────────────────────
    // The active theme's desktop widgets (clock/visualizer/sysinfo/lyrics),
    // scanned when the sheet opens. Rows only appear for slots the theme
    // actually ships — except the visualizer, which falls back to the Arch
    // triangle and so always has something to turn off. State lives in the
    // ThemeSettings singleton; the loaders unmount live when a toggle flips.
    property var themeSlots: []
    property string themeDirNow: ""
    readonly property string themeName: themeDirNow ? themeDirNow.split("/").pop() : ""

    // ── keep-laptop-awake setting ──────────────────────────────────────
    // Holds a logind block-inhibitor on handle-lid-switch while on, so
    // closing the lid does nothing. Persisted across shell restarts.
    property bool keepAwake: false

    // ── auto-lock setting ───────────────────────────────────────────────
    // hypridle always runs as a child process (it owns before_sleep, so the
    // lock holds across suspend even with auto-lock off). The toggle only
    // flips the idle listeners, via a runtime flag the conf listeners read.
    property bool autoLock: false

    // Captured at open() time so follow_mouse can't remap the window mid-use.
    property var targetScreen: null
    screen: targetScreen

    WlrLayershell.namespace: "quickshell-shortcuts"
    WlrLayershell.layer: WlrLayer.Overlay
    // Grab the keyboard only while open so Esc/keys reach the card; the
    // focused window keeps the keyboard the rest of the time.
    WlrLayershell.keyboardFocus: open ? WlrKeyboardFocus.Exclusive : WlrKeyboardFocus.None

    anchors { top: true; bottom: true; left: true; right: true }
    exclusionMode: ExclusionMode.Ignore
    color: "transparent"
    visible: open || closing

    readonly property string iconArch: String.fromCodePoint(0xF303) // nf-linux-archlinux

    // Bare modifier taps shouldn't close the sheet (otherwise letting go of Super
    // would shut it the instant it opens).
    readonly property var modifierKeys: [
        Qt.Key_Shift, Qt.Key_Control, Qt.Key_Alt, Qt.Key_AltGr,
        Qt.Key_Meta, Qt.Key_Super_L, Qt.Key_Super_R,
        Qt.Key_CapsLock, Qt.Key_NumLock, Qt.Key_ScrollLock
    ]

    // ── the cheat-sheet data ────────────────────────────────────────────
    // `columns` is an array of columns; each column is an array of sections;
    // each section has a title and a list of binds. A bind's `keys` is the list
    // of keycap labels rendered left→right with "+" between them.
    readonly property var columns: [
        [
            { title: "Apps", binds: [
                { keys: ["Super", "T"],          desc: "Terminal" },
                { keys: ["Super", "W"],          desc: "Browser" },
                { keys: ["Super", "E"],          desc: "Files" },
                { keys: ["Super", "C"],          desc: "Code" },
                { keys: ["Super", "G"],          desc: "GitHub Desktop" },
                { keys: ["Super", "Shift", "C"], desc: "Claude" },
                { keys: ["Super", "S"],          desc: "Frostify" },
                { keys: ["Super", "R"],          desc: "App launcher" }
            ]},
            { title: "System", binds: [
                { keys: ["Super", "M"],          desc: "Control center" },
                { keys: ["Super", "V"],          desc: "Clipboard history" },
                { keys: ["Super", "Shift", "T"], desc: "Themes" },
                { keys: ["Super", "Shift", "R"], desc: "Restart shell" },
                { keys: ["Super", "L"],          desc: "Lock screen" },
                { keys: ["Super", "Shift", "S"], desc: "Screenshot region" },
                { keys: ["Super", "/"],          desc: "This sheet" },
                { keys: ["Super", "Shift", "/"], desc: "Settings" },
                { keys: ["Super", "."],          desc: "Pin system info" }
            ]},
            { title: "Workspaces", binds: [
                { keys: ["Super", "1 – 5"],            desc: "Switch workspace" },
                { keys: ["Super", "Scroll"],          desc: "Cycle this monitor" },
                { keys: ["Super", "Ctrl", "← →"],     desc: "Prev / next" },
                { keys: ["Super", "Ctrl", "Shift", "← →"], desc: "Carry window" }
            ]}
        ],
        [
            { title: "Windows", binds: [
                { keys: ["Super", "← → ↑ ↓"],        desc: "Focus window" },
                { keys: ["Super", "Q"],              desc: "Close window" },
                { keys: ["Super", "F"],              desc: "Toggle float" },
                { keys: ["Super", "Drag"],           desc: "Move window" },
                { keys: ["Super", "Right-drag"],     desc: "Resize window" },
                { keys: ["Super", "Shift", "← →"],   desc: "Send to monitor" },
                { keys: ["Super", "Shift", "↑ ↓"],   desc: "Move in layout" }
            ]},
            { title: "Lyrics", binds: [
                { keys: ["Super", "]"],          desc: "Sync later" },
                { keys: ["Super", "["],          desc: "Sync earlier" },
                { keys: ["Super", "Shift", "\\"], desc: "Reset sync" }
            ]}
        ]
    ]

    // ── persistence + inhibitor ─────────────────────────────────────────
    // State file is read synchronously at startup so the inhibitor comes back
    // up in the same state it was left in.
    FileView {
        id: stateFile
        path: Quickshell.stateDir + "/keep-awake"
        blockLoading: true
        preload: true
        printErrors: false
    }

    function setKeepAwake(v) {
        root.keepAwake = v
        stateFile.setText(v ? "1\n" : "0\n")
    }

    FileView {
        id: autoLockFile
        path: Quickshell.stateDir + "/auto-lock"
        blockLoading: true
        preload: true
        printErrors: false
    }

    // mirror for hypridle's listeners (runtime dir clears on reboot, so it's
    // rewritten from the state file every startup)
    readonly property string autoLockFlagPath: {
        const rt = Quickshell.env("XDG_RUNTIME_DIR")
        return ((rt && String(rt).length) ? String(rt) : "/tmp") + "/qs-autolock"
    }
    FileView {
        id: autoLockFlag
        path: root.autoLockFlagPath
        printErrors: false
    }

    function setAutoLock(v) {
        root.autoLock = v
        autoLockFile.setText(v ? "1\n" : "0\n")
        autoLockFlag.setText(v ? "1\n" : "0\n")
    }

    Component.onCompleted: {
        root.keepAwake = stateFile.text().trim() === "1"
        root.autoLock = autoLockFile.text().trim() === "1"
        autoLockFlag.setText(root.autoLock ? "1\n" : "0\n")
    }

    Process {
        id: slotProc
        stdout: StdioCollector {
            onStreamFinished: {
                const have = text.trim().split("\n").filter(s => s !== "")
                const defs = [
                    { slot: "clock",   label: "Clock",       desc: "The theme's desktop clock.",              needsFile: true },
                    { slot: "cava",    label: "Visualizer",  desc: "The audio visualizer on the desktop.",    needsFile: false },
                    { slot: "sysinfo", label: "System info", desc: "The ambient system readout.",             needsFile: true },
                    { slot: "lyrics",  label: "Lyrics",      desc: "Live desktop lyrics while music plays.",  needsFile: true }
                ]
                root.themeSlots = defs.filter(d => !d.needsFile || have.indexOf(d.slot) !== -1)
            }
        }
    }
    // command built at call time, not bound — same one-behind trap as the loaders
    function scanThemeSlots() {
        root.themeDirNow = ActiveTheme.dirFor(root.targetScreen ? root.targetScreen.name : "")
        if (root.themeDirNow === "") { root.themeSlots = []; return }
        slotProc.command = ["bash", "-c",
            'd="$1"; for s in clock sysinfo cava lyrics; do [ -f "$d/$s.qml" ] && echo "$s"; done; true',
            "_", root.themeDirNow]
        slotProc.running = true
    }

    // While running, logind ignores the lid switch. Killed on shell exit, which
    // releases the lock — Component.onCompleted re-arms it on next start.
    Process {
        id: lidInhibitor
        running: root.keepAwake
        command: ["systemd-inhibit",
                  "--what=handle-lid-switch",
                  "--who=frostify shell",
                  "--why=Keep laptop awake when the lid is shut",
                  "--mode=block",
                  "sleep", "infinity"]
    }

    Process {
        id: idleDaemon
        running: true
        command: ["hypridle"]
    }

    // ── marketplace: catalog, installed-scan, install ───────────────────
    // fetch index.json (network first, cached copy as fallback). command built
    // at call time, not bound — the one-behind trap the loaders all warn about.
    Process {
        id: catalogProc
        stdout: StdioCollector { onStreamFinished: root.onCatalog(text) }
    }
    function loadCatalog() {
        if (catalogProc.running) return
        root.mktLoading = true
        root.mktError = ""
        catalogProc.command = ["bash", "-c",
            'cache="$1/index.json"; ' +
            'if out=$(curl -fsSL -m 8 -A "hypr-marketplace" "$2"); then ' +
            '  mkdir -p "$1"; printf "%s" "$out" > "$cache"; printf "%s" "$out"; ' +
            'elif [ -f "$cache" ]; then cat "$cache"; else printf NETERR; fi',
            "_", root.mktCacheDir, root.mktRawBase + "index.json"]
        catalogProc.running = true
    }
    function onCatalog(text) {
        root.mktLoading = false
        const t = (text || "").trim()
        if (t === "" || t === "NETERR") { root.mktError = "couldn't reach the store"; return }
        try {
            const j = JSON.parse(t)
            root.mktThemes = j.themes || []
            root.mktCommit = j.commit || root.mktBranch
            root.mktError = ""
        } catch (e) { root.mktError = "the catalog looked malformed" }
        root.scanInstalled()
    }

    Process {
        id: installedProc
        stdout: StdioCollector {
            onStreamFinished: {
                const m = {}
                for (const line of (text || "").split("\n")) { const s = line.trim(); if (s) m[s] = true }
                root.mktInstalled = m
            }
        }
    }
    function scanInstalled() {
        installedProc.command = ["bash", "-c",
            'for d in "$HOME"/.config/themes/*/; do [ -d "$d" ] && basename "$d"; done; true']
        installedProc.running = true
    }

    // one install at a time; progress lines drive the row's bar
    Process {
        id: installProc
        stdout: SplitParser { onRead: (line) => root.onInstallLine(line) }
    }
    function installTheme(t) {
        if (root.mktBusy !== "" || installProc.running || !t || !t.files) return
        root.mktBusy = t.name
        root.mktError = ""
        const start = Object.assign({}, root.mktProgress)
        start[t.name] = { done: 0, total: t.files.length }
        root.mktProgress = start
        const paths = t.files.map(f => f.path)
        installProc.command = ["bash", root.mktScript, root.mktRepo, root.mktBranch,
                               t.name, root.mktCommit].concat(paths)
        installProc.running = true
    }
    function onInstallLine(line) {
        const p = (line || "").split(" ")
        if (p[0] === "PROG") {
            const m = Object.assign({}, root.mktProgress)
            m[root.mktBusy] = { done: parseInt(p[1]), total: parseInt(p[2]) }
            root.mktProgress = m
        } else if (p[0] === "DONE") {
            const inst = Object.assign({}, root.mktInstalled); inst[root.mktBusy] = true
            root.mktInstalled = inst
            const m = Object.assign({}, root.mktProgress); delete m[root.mktBusy]
            root.mktProgress = m
            root.mktBusy = ""
        } else if (p[0] === "ERR") {
            root.mktError = line.substring(4)
            const m = Object.assign({}, root.mktProgress); delete m[root.mktBusy]
            root.mktProgress = m
            root.mktBusy = ""
        }
    }
    function progressFor(name) { return root.mktProgress[name] ?? null }
    function isInstalled(name) { return root.mktInstalled[name] === true }

    // the theme on the desktop right now — refuse to delete it out from under
    // the running shell (awww would be left pointing at a deleted wallpaper)
    function isActive(name) {
        const d = ActiveTheme.focusedDir
        return d !== "" && d.substring(d.lastIndexOf("/") + 1) === name
    }

    Process {
        id: removeProc
        stdout: StdioCollector { onStreamFinished: root.scanInstalled() }
    }
    function uninstallTheme(name) {
        if (installProc.running || removeProc.running) return
        if (root.isActive(name)) return
        // command built at call time; name is validated to a safe slug so the
        // rm can never wander outside ~/.config/themes
        removeProc.command = ["bash", "-c",
            'n="$1"; case "$n" in *[!a-zA-Z0-9_-]*|"") exit 0;; esac; ' +
            'rm -rf -- "$HOME/.config/themes/$n"; echo done',
            "_", name]
        removeProc.running = true
        root.mktArmedRemove = ""
    }

    // Enter on the selected store row: install if absent, arm→confirm remove if
    // present. install needs no confirm; removal is destructive so it double-taps.
    function mktActivate() {
        const t = root.mktThemes[root.mktRow]
        if (!t || root.mktBusy !== "") return
        if (root.isInstalled(t.name)) {
            if (root.isActive(t.name)) return                 // can't remove what's live
            if (root.mktArmedRemove === t.name) root.uninstallTheme(t.name)
            else root.mktArmedRemove = t.name                 // first press arms it
        } else {
            root.mktArmedRemove = ""
            root.installTheme(t)
        }
    }
    function mktMove(d) {
        if (root.mktThemes.length === 0) return
        root.mktArmedRemove = ""                              // moving cancels a pending remove
        root.mktRow = Math.max(0, Math.min(root.mktThemes.length - 1, root.mktRow + d))
        mktList.positionViewAtIndex(root.mktRow, ListView.Contain)
    }

    // entering the store: refresh the catalog + installed set, reset the cursor,
    // land at the top. Called both on an in-sheet tab switch AND from openMenu
    // (reopening straight onto tab 2 doesn't change `tab`, so onTabChanged alone
    // would miss it). loadCatalog's own running-guard makes a double call cheap.
    function enterMarketplace() {
        if (!mktLoading) loadCatalog()      // refresh each open (cache shows if offline)
        scanInstalled()
        mktRow = 0
        mktArmedRemove = ""
        Qt.callLater(() => mktList.positionViewAtBeginning())
    }

    // ── self-update: fetch + compare HEAD to the tracking branch ─────────
    Process {
        id: updCheckProc
        stdout: StdioCollector { onStreamFinished: root.onUpdCheck(text) }
    }
    function checkUpdates() {
        if (updCheckProc.running || root.updState === "pulling") return
        root.updState = "checking"
        // tab-separated: OK<t><behind><t><sha (reldate)> | OFFLINE<t><sha (reldate)> | ERR
        // the version reads as one field ("abc1234 (3 days ago)") so it survives the split
        updCheckProc.command = ["bash", "-c",
            'cd "$1" 2>/dev/null && git rev-parse --git-dir >/dev/null 2>&1 || { printf ERR; exit 0; }; ' +
            'loc="$(git log -1 --format="%h (%cr)" 2>/dev/null)"; ' +
            'if ! git fetch --quiet 2>/dev/null; then printf "OFFLINE\\t%s" "$loc"; exit 0; fi; ' +
            'up="$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null || echo origin/main)"; ' +
            'n="$(git rev-list --count HEAD.."$up" 2>/dev/null || echo 0)"; ' +
            'printf "OK\\t%s\\t%s" "$n" "$loc"',
            "_", root.updRepo]
        updCheckProc.running = true
    }
    function onUpdCheck(text) {
        const parts = (text || "").trim().split("\t")
        if (parts[0] === "ERR" || parts[0] === "") { root.updState = "error"; return }
        if (parts[0] === "OFFLINE") { root.updLocal = parts[1] || ""; root.updState = "offline"; return }
        root.updBehind = parseInt(parts[1]) || 0
        root.updLocal = parts[2] || ""
        root.updState = root.updBehind > 0 ? "behind" : "uptodate"
        // notify once when a new update appears (again only if more land later)
        if (root.updBehind > root.updNotifiedBehind) {
            root.updNotifiedBehind = root.updBehind
            Quickshell.execDetached(["notify-send", "-a", "world80",
                "-i", "software-update-available", "world80 update available",
                root.updBehind + " new commit" + (root.updBehind > 1 ? "s" : "")
                    + " — open Super+/ → Settings to update"])
        } else if (root.updBehind === 0) {
            root.updNotifiedBehind = 0     // reset after a successful update
        }
    }

    // check on launch (after a short settle) and every 6 hours after, in the
    // background — the Settings banner just reflects the latest result.
    Timer {
        interval: 120000
        running: true
        repeat: true
        onTriggered: { root.checkUpdates(); interval = 6 * 3600 * 1000 }
    }

    Process {
        id: updPullProc
        stdout: SplitParser { onRead: (line) => { if (line === "__ok__") root.updState = "done"
                                                  else if (line === "__fail__") root.updState = "error" } }
    }
    function doUpdate() {
        if (root.updState !== "behind" || updPullProc.running) return
        root.updState = "pulling"
        // ff-only so a diverged/locally-edited clone fails safe instead of merging
        updPullProc.command = ["bash", "-c",
            'cd "$1" || { echo __fail__; exit 0; }; ' +
            'if git pull --ff-only >/dev/null 2>&1; then echo __ok__; else echo __fail__; fi',
            "_", root.updRepo]
        updPullProc.running = true
    }

    onTabChanged: {
        if (tab === 2) enterMarketplace()
        else if (tab === 1 && (updState === "idle" || updState === "error" || updState === "offline"))
            checkUpdates()
    }

    // ── lifecycle ───────────────────────────────────────────────────────
    function openMenu(which) {
        const m = Hyprland.focusedMonitor
        targetScreen = m ? (Quickshell.screens.find(s => s.name === m.name) ?? null) : null
        closing = false
        tab = which
        settingsRow = 0
        scanThemeSlots()
        if (which === 2) enterMarketplace()   // reopening onto tab 2 won't fire onTabChanged
        else if (which === 1 && (updState === "idle" || updState === "error" || updState === "offline"))
            checkUpdates()
        open = true
        Qt.callLater(card.forceActiveFocus)
    }
    function closeMenu() {
        if (!open) return
        open = false
        closing = true
        closeHold.restart()
    }
    Timer { id: closeHold; interval: 220; onTriggered: root.closing = false }

    IpcHandler {
        target: "shortcuts"
        function toggle(): void { root.open ? root.closeMenu() : root.openMenu(0) }
        function settings(): void {
            if (root.open && root.tab === 1) root.closeMenu()
            else root.openMenu(1)
        }
        function marketplace(): void {
            if (root.open && root.tab === 2) root.closeMenu()
            else root.openMenu(2)
        }
        // flip auto-lock without opening the sheet (scripts / future keybind)
        function autolock(): void { root.setAutoLock(!root.autoLock) }
    }

    // ── scrim: transparent (no dimming), click-outside to dismiss ───────
    MouseArea {
        anchors.fill: parent
        enabled: root.open
        onClicked: root.closeMenu()
    }

    Item {
        id: morph
        width: card.width
        height: card.height
        anchors.centerIn: parent
        opacity: 0
        scale: 0.92
        transformOrigin: Item.Center

        states: State {
            name: "shown"
            when: root.open
            PropertyChanges { target: morph; opacity: 1; scale: 1 }
        }

        transitions: [
            Transition {
                to: "shown"
                ParallelAnimation {
                    NumberAnimation { property: "opacity"; duration: 220; easing.type: Easing.OutCubic }
                    SpringAnimation { property: "scale"; spring: 3; damping: 0.34; epsilon: 0.001 }
                }
            },
            Transition {
                from: "shown"
                ParallelAnimation {
                    NumberAnimation { property: "opacity"; duration: 170; easing.type: Easing.InCubic }
                    NumberAnimation { property: "scale"; duration: 170; easing.type: Easing.InCubic }
                }
            }
        ]

        Rectangle {
            id: card
            width: 816
            height: content.implicitHeight + 40
            radius: Theme.popupRadius
            color: Theme.glassBg
            border.color: Theme.glassBorder
            border.width: 1
            focus: true

            Behavior on height { NumberAnimation { duration: 160; easing.type: Easing.OutCubic } }

            // Esc / click-outside always close. Left/Right switch tabs. The
            // Settings tab is interactive (Up/Down + Enter/Space), so only the
            // passive Shortcuts tab keeps the old "press anything to dismiss".
            Keys.onPressed: (e) => {
                if (e.key === Qt.Key_Escape) { root.closeMenu(); e.accepted = true; return }
                if (e.key === Qt.Key_Left)  { root.tab = Math.max(0, root.tab - 1); e.accepted = true; return }
                if (e.key === Qt.Key_Right) { root.tab = Math.min(root.tabCount - 1, root.tab + 1); e.accepted = true; return }

                // Marketplace tab: Up/Down move the cursor, Enter installs (or
                // arms→confirms a remove); other keys are swallowed so a stray
                // press doesn't dismiss the store.
                if (root.tab === 2) {
                    if (e.key === Qt.Key_Up)   { root.mktMove(-1); e.accepted = true; return }
                    if (e.key === Qt.Key_Down) { root.mktMove(1);  e.accepted = true; return }
                    if (e.key === Qt.Key_Return || e.key === Qt.Key_Enter) {
                        root.mktActivate(); e.accepted = true; return
                    }
                    if (root.mktArmedRemove !== "") { root.mktArmedRemove = ""; e.accepted = true; return }
                    e.accepted = true
                    return
                }

                if (root.tab === 1) {
                    if (e.key === Qt.Key_Up) {
                        root.settingsRow = Math.max(0, root.settingsRow - 1); e.accepted = true; return
                    }
                    if (e.key === Qt.Key_Down) {
                        root.settingsRow = Math.min(root.settingsCount - 1, root.settingsRow + 1); e.accepted = true; return
                    }
                    if (e.key === Qt.Key_Space || e.key === Qt.Key_Return || e.key === Qt.Key_Enter) {
                        if (root.settingsRow === 0) root.setKeepAwake(!root.keepAwake)
                        else if (root.settingsRow === 1) root.setAutoLock(!root.autoLock)
                        else if (root.settingsRow - 2 < root.themeSlots.length)
                            ThemeSettings.toggle(root.themeDirNow, root.themeSlots[root.settingsRow - 2].slot)
                        e.accepted = true; return
                    }
                    e.accepted = true   // swallow stray keys instead of closing
                    return
                }

                // Shortcuts tab: any non-modifier key dismisses.
                if (!root.modifierKeys.includes(e.key)) { root.closeMenu(); e.accepted = true }
            }

            // Swallow clicks on the card so they don't fall through to the scrim.
            MouseArea { anchors.fill: parent }

            // top inner highlight, matching the control popup
            Rectangle {
                anchors.left: parent.left
                anchors.right: parent.right
                anchors.top: parent.top
                anchors.leftMargin: parent.radius
                anchors.rightMargin: parent.radius
                anchors.topMargin: 1
                height: 1
                color: Theme.glassHighlight
            }

            Column {
                id: content
                anchors.fill: parent
                anchors.margins: 20
                spacing: 16

                // ── header ──
                Item {
                    width: parent.width
                    height: 22

                    Row {
                        anchors.left: parent.left
                        anchors.verticalCenter: parent.verticalCenter
                        spacing: 8

                        Text {
                            anchors.verticalCenter: parent.verticalCenter
                            text: root.iconArch
                            color: Theme.accent
                            font.family: Theme.icon
                            font.pixelSize: 16
                        }

                        // tab switcher
                        Row {
                            anchors.verticalCenter: parent.verticalCenter
                            spacing: 4

                            Repeater {
                                model: ["Keyboard Shortcuts", "Settings", "Marketplace"]

                                delegate: Rectangle {
                                    id: tabChip
                                    required property int index
                                    required property var modelData
                                    readonly property bool current: root.tab === index
                                    height: 24
                                    width: tabText.implicitWidth + 22
                                    radius: 7
                                    color: current ? Theme.rowSelected
                                                   : (tabHover.hovered ? Theme.rowHover : "transparent")
                                    border.color: current ? Theme.glassBorder : "transparent"
                                    border.width: 1

                                    Text {
                                        id: tabText
                                        anchors.centerIn: parent
                                        text: tabChip.modelData
                                        color: tabChip.current ? Theme.textBright : Theme.textMuted
                                        font.pixelSize: 13
                                        font.weight: tabChip.current ? Font.DemiBold : Font.Normal
                                    }

                                    HoverHandler { id: tabHover }
                                    MouseArea {
                                        anchors.fill: parent
                                        cursorShape: Qt.PointingHandCursor
                                        onClicked: root.tab = tabChip.index
                                    }
                                }
                            }
                        }
                    }

                    Text {
                        anchors.right: parent.right
                        anchors.verticalCenter: parent.verticalCenter
                        text: root.tab === 2 ? "↑↓ select · ↵ install · esc"
                             : root.tab === 1 ? "← → switch · Esc close"
                             : "Esc to close"
                        color: Theme.textMuted
                        font.pixelSize: 11
                    }
                }

                Rectangle { width: parent.width; height: 1; color: Theme.divider }

                // ── Shortcuts tab: two columns of sections ──
                Row {
                    width: parent.width
                    spacing: 36
                    visible: root.tab === 0

                    Repeater {
                        model: root.columns

                        delegate: Column {
                            id: col
                            required property var modelData    // array of sections
                            width: (parent.width - parent.spacing) / 2
                            spacing: 18

                            Repeater {
                                model: col.modelData

                                delegate: Column {
                                    id: section
                                    required property var modelData   // { title, binds }
                                    width: parent.width
                                    spacing: 7

                                    Text {
                                        text: section.modelData.title
                                        color: Theme.accent
                                        font.pixelSize: 11
                                        font.weight: Font.DemiBold
                                        font.capitalization: Font.AllUppercase
                                        font.letterSpacing: 1.4
                                    }

                                    Repeater {
                                        model: section.modelData.binds

                                        delegate: Item {
                                            id: bindRow
                                            required property var modelData   // { keys, desc }
                                            width: parent.width
                                            height: 26

                                            Text {
                                                anchors.left: parent.left
                                                anchors.verticalCenter: parent.verticalCenter
                                                width: Math.max(0, parent.width - caps.width - 14)
                                                text: bindRow.modelData.desc
                                                color: Theme.textSecondary
                                                font.pixelSize: 13
                                                elide: Text.ElideRight
                                            }

                                            Row {
                                                id: caps
                                                anchors.right: parent.right
                                                anchors.verticalCenter: parent.verticalCenter
                                                spacing: 5

                                                Repeater {
                                                    model: bindRow.modelData.keys

                                                    delegate: Row {
                                                        id: chip
                                                        required property int index
                                                        required property var modelData   // a key label
                                                        spacing: 5

                                                        Text {
                                                            visible: chip.index > 0
                                                            anchors.verticalCenter: parent.verticalCenter
                                                            text: "+"
                                                            color: Theme.textMuted
                                                            font.pixelSize: 12
                                                        }

                                                        Rectangle {
                                                            anchors.verticalCenter: parent.verticalCenter
                                                            height: 22
                                                            width: Math.max(22, keyLabel.implicitWidth + 14)
                                                            radius: 6
                                                            color: Theme.rowSelected
                                                            border.color: Theme.glassBorder
                                                            border.width: 1

                                                            Text {
                                                                id: keyLabel
                                                                anchors.centerIn: parent
                                                                text: chip.modelData
                                                                color: Theme.textBright
                                                                font.family: Theme.mono
                                                                font.pixelSize: 12
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                // ── Settings tab ──
                Column {
                    width: parent.width
                    spacing: 10
                    visible: root.tab === 1

                    // ── engine update banner (checks ~/dotfiles vs GitHub) ──
                    Rectangle {
                        width: parent.width
                        height: 56
                        radius: 10
                        color: "transparent"
                        border.color: root.updState === "behind" ? Theme.accent : Theme.glassBorder
                        border.width: 1

                        Row {
                            anchors.left: parent.left
                            anchors.leftMargin: 16
                            anchors.right: updBtn.left
                            anchors.rightMargin: 12
                            anchors.verticalCenter: parent.verticalCenter
                            spacing: 12

                            Text {
                                anchors.verticalCenter: parent.verticalCenter
                                text: root.updState === "behind" ? "⭳" : "⟳"
                                color: root.updState === "behind" ? Theme.accent : Theme.textMuted
                                font.pixelSize: 17
                            }
                            Column {
                                anchors.verticalCenter: parent.verticalCenter
                                spacing: 3
                                Text {
                                    text: "world80"
                                    color: Theme.textBright
                                    font.pixelSize: 14
                                    font.weight: Font.DemiBold
                                }
                                Text {
                                    text: {
                                        switch (root.updState) {
                                        case "checking": return "checking for updates…"
                                        case "behind":   return root.updBehind + " update" + (root.updBehind > 1 ? "s" : "") + " available"
                                        case "pulling":  return "downloading update…"
                                        case "done":     return "updated — press Super+Shift+R to restart the shell"
                                        case "offline":  return "offline · " + root.updLocal
                                        case "error":    return "couldn't check — needs a git clone + network"
                                        default:         return "up to date · " + root.updLocal
                                        }
                                    }
                                    color: root.updState === "done" ? Theme.accent : Theme.textMuted
                                    font.pixelSize: 11
                                    textFormat: Text.PlainText
                                    elide: Text.ElideRight
                                }
                            }
                        }

                        // action: download when behind, else re-check (hidden while working)
                        Rectangle {
                            id: updBtn
                            anchors.right: parent.right
                            anchors.rightMargin: 16
                            anchors.verticalCenter: parent.verticalCenter
                            readonly property bool isUpdate: root.updState === "behind"
                            visible: root.updState === "behind" || root.updState === "uptodate"
                                     || root.updState === "offline" || root.updState === "error"
                            width: updBtnT.implicitWidth + 26
                            height: 30
                            radius: 8
                            color: isUpdate ? (updBtnMa.containsMouse ? Theme.accent : Theme.rowSelected)
                                            : (updBtnMa.containsMouse ? Theme.rowSelected : Theme.rowHover)
                            border.color: isUpdate ? Theme.accent : Theme.glassBorder
                            border.width: 1
                            Behavior on color { ColorAnimation { duration: 140 } }
                            Text {
                                id: updBtnT
                                anchors.centerIn: parent
                                text: updBtn.isUpdate ? "download" : "check"
                                color: Theme.textBright
                                font.pixelSize: 12
                                font.weight: updBtn.isUpdate ? Font.DemiBold : Font.Normal
                            }
                            MouseArea {
                                id: updBtnMa
                                anchors.fill: parent
                                hoverEnabled: true
                                cursorShape: Qt.PointingHandCursor
                                onClicked: updBtn.isUpdate ? root.doUpdate() : root.checkUpdates()
                            }
                        }
                        Text {
                            anchors.right: parent.right
                            anchors.rightMargin: 18
                            anchors.verticalCenter: parent.verticalCenter
                            visible: root.updState === "checking" || root.updState === "pulling"
                            text: "…"
                            color: Theme.textMuted
                            font.pixelSize: 18
                        }
                    }

                    // row 0 — keep laptop awake when lid shut
                    Rectangle {
                        width: parent.width
                        height: 56
                        radius: 10
                        color: root.settingsRow === 0 ? Theme.rowSelected
                                                      : (awakeHover.hovered ? Theme.rowHover : "transparent")
                        border.color: root.settingsRow === 0 ? Theme.glassBorder : "transparent"
                        border.width: 1

                        HoverHandler { id: awakeHover }
                        MouseArea {
                            anchors.fill: parent
                            cursorShape: Qt.PointingHandCursor
                            onClicked: { root.settingsRow = 0; root.setKeepAwake(!root.keepAwake) }
                        }

                        Column {
                            anchors.left: parent.left
                            anchors.leftMargin: 16
                            anchors.right: toggle.left
                            anchors.rightMargin: 16
                            anchors.verticalCenter: parent.verticalCenter
                            spacing: 3

                            Text {
                                text: "Keep laptop awake when lid is shut"
                                color: Theme.textBright
                                font.pixelSize: 14
                                font.weight: Font.DemiBold
                            }
                            Text {
                                width: parent.width
                                text: "Hold a system lock so closing the lid won't suspend."
                                color: Theme.textMuted
                                font.pixelSize: 11
                                elide: Text.ElideRight
                            }
                        }

                        // pill toggle
                        Rectangle {
                            id: toggle
                            anchors.right: parent.right
                            anchors.rightMargin: 16
                            anchors.verticalCenter: parent.verticalCenter
                            width: 44
                            height: 24
                            radius: 12
                            color: root.keepAwake ? Theme.accent : Theme.trackBg
                            border.color: root.keepAwake ? Theme.accent : Theme.glassBorder
                            border.width: 1
                            Behavior on color { ColorAnimation { duration: 140 } }

                            Rectangle {
                                width: 18
                                height: 18
                                radius: 9
                                color: root.keepAwake ? Theme.textBright : Theme.textMuted
                                anchors.verticalCenter: parent.verticalCenter
                                x: root.keepAwake ? parent.width - width - 3 : 3
                                Behavior on x { NumberAnimation { duration: 140; easing.type: Easing.OutCubic } }
                                Behavior on color { ColorAnimation { duration: 140 } }
                            }
                        }
                    }

                    // row 1 — auto-lock on idle
                    Rectangle {
                        width: parent.width
                        height: 56
                        radius: 10
                        color: root.settingsRow === 1 ? Theme.rowSelected
                                                      : (lockHover.hovered ? Theme.rowHover : "transparent")
                        border.color: root.settingsRow === 1 ? Theme.glassBorder : "transparent"
                        border.width: 1

                        HoverHandler { id: lockHover }
                        MouseArea {
                            anchors.fill: parent
                            cursorShape: Qt.PointingHandCursor
                            onClicked: { root.settingsRow = 1; root.setAutoLock(!root.autoLock) }
                        }

                        Column {
                            anchors.left: parent.left
                            anchors.leftMargin: 16
                            anchors.right: lockToggle.left
                            anchors.rightMargin: 16
                            anchors.verticalCenter: parent.verticalCenter
                            spacing: 3

                            Text {
                                text: "Auto-lock when idle"
                                color: Theme.textBright
                                font.pixelSize: 14
                                font.weight: Font.DemiBold
                            }
                            Text {
                                width: parent.width
                                text: "Lock after 5 minutes idle, screens off after 10."
                                color: Theme.textMuted
                                font.pixelSize: 11
                                elide: Text.ElideRight
                            }
                        }

                        Rectangle {
                            id: lockToggle
                            anchors.right: parent.right
                            anchors.rightMargin: 16
                            anchors.verticalCenter: parent.verticalCenter
                            width: 44
                            height: 24
                            radius: 12
                            color: root.autoLock ? Theme.accent : Theme.trackBg
                            border.color: root.autoLock ? Theme.accent : Theme.glassBorder
                            border.width: 1
                            Behavior on color { ColorAnimation { duration: 140 } }

                            Rectangle {
                                width: 18
                                height: 18
                                radius: 9
                                color: root.autoLock ? Theme.textBright : Theme.textMuted
                                anchors.verticalCenter: parent.verticalCenter
                                x: root.autoLock ? parent.width - width - 3 : 3
                                Behavior on x { NumberAnimation { duration: 140; easing.type: Easing.OutCubic } }
                                Behavior on color { ColorAnimation { duration: 140 } }
                            }
                        }
                    }

                    // ── per-theme widget toggles ──
                    Item {
                        width: parent.width
                        height: 24
                        visible: root.themeSlots.length > 0

                        Rectangle {
                            anchors.left: parent.left
                            anchors.right: sectionTitle.left
                            anchors.rightMargin: 10
                            anchors.verticalCenter: parent.verticalCenter
                            height: 1
                            color: Theme.divider
                        }
                        Text {
                            id: sectionTitle
                            anchors.right: parent.right
                            anchors.verticalCenter: parent.verticalCenter
                            text: root.themeName.toUpperCase() + " WIDGETS"
                            color: Theme.accent
                            font.pixelSize: 11
                            font.weight: Font.DemiBold
                            font.letterSpacing: 1.4
                        }
                    }

                    Repeater {
                        model: root.themeSlots

                        delegate: Rectangle {
                            id: slotRow
                            required property int index
                            required property var modelData
                            readonly property int rowIdx: 2 + index
                            readonly property bool isOn: ThemeSettings.on(root.themeDirNow, modelData.slot)

                            width: parent.width
                            height: 56
                            radius: 10
                            color: root.settingsRow === rowIdx ? Theme.rowSelected
                                                               : (slotHover.hovered ? Theme.rowHover : "transparent")
                            border.color: root.settingsRow === rowIdx ? Theme.glassBorder : "transparent"
                            border.width: 1

                            HoverHandler { id: slotHover }
                            MouseArea {
                                anchors.fill: parent
                                cursorShape: Qt.PointingHandCursor
                                onClicked: {
                                    root.settingsRow = slotRow.rowIdx
                                    ThemeSettings.toggle(root.themeDirNow, slotRow.modelData.slot)
                                }
                            }

                            Column {
                                anchors.left: parent.left
                                anchors.leftMargin: 16
                                anchors.right: slotToggle.left
                                anchors.rightMargin: 16
                                anchors.verticalCenter: parent.verticalCenter
                                spacing: 3

                                Text {
                                    text: slotRow.modelData.label
                                    color: Theme.textBright
                                    font.pixelSize: 14
                                    font.weight: Font.DemiBold
                                }
                                Text {
                                    width: parent.width
                                    text: slotRow.modelData.desc
                                    color: Theme.textMuted
                                    font.pixelSize: 11
                                    elide: Text.ElideRight
                                }
                            }

                            Rectangle {
                                id: slotToggle
                                anchors.right: parent.right
                                anchors.rightMargin: 16
                                anchors.verticalCenter: parent.verticalCenter
                                width: 44
                                height: 24
                                radius: 12
                                color: slotRow.isOn ? Theme.accent : Theme.trackBg
                                border.color: slotRow.isOn ? Theme.accent : Theme.glassBorder
                                border.width: 1
                                Behavior on color { ColorAnimation { duration: 140 } }

                                Rectangle {
                                    width: 18
                                    height: 18
                                    radius: 9
                                    color: slotRow.isOn ? Theme.textBright : Theme.textMuted
                                    anchors.verticalCenter: parent.verticalCenter
                                    x: slotRow.isOn ? parent.width - width - 3 : 3
                                    Behavior on x { NumberAnimation { duration: 140; easing.type: Easing.OutCubic } }
                                    Behavior on color { ColorAnimation { duration: 140 } }
                                }
                            }
                        }
                    }
                }

                // ── Marketplace tab ──
                Item {
                    width: parent.width
                    height: 470
                    visible: root.tab === 2

                    // empty / loading / error state (no rows yet)
                    Column {
                        anchors.centerIn: parent
                        spacing: 10
                        visible: root.mktThemes.length === 0
                        Text {
                            anchors.horizontalCenter: parent.horizontalCenter
                            text: root.mktLoading ? "opening the store…"
                                 : root.mktError !== "" ? root.mktError
                                 : "no themes found"
                            color: Theme.textMuted
                            font.pixelSize: 13
                        }
                        Rectangle {
                            anchors.horizontalCenter: parent.horizontalCenter
                            visible: !root.mktLoading && root.mktError !== ""
                            width: retryText.implicitWidth + 24; height: 30; radius: 8
                            color: retryMa.containsMouse ? Theme.rowSelected : Theme.rowHover
                            border.color: Theme.glassBorder; border.width: 1
                            Text { id: retryText; anchors.centerIn: parent; text: "try again"
                                   color: Theme.textBright; font.pixelSize: 12 }
                            MouseArea { id: retryMa; anchors.fill: parent; hoverEnabled: true
                                cursorShape: Qt.PointingHandCursor; onClicked: root.loadCatalog() }
                        }
                    }

                    ListView {
                        id: mktList
                        anchors.fill: parent
                        visible: root.mktThemes.length > 0
                        model: root.mktThemes
                        clip: true
                        spacing: 8
                        currentIndex: -1
                        boundsBehavior: Flickable.StopAtBounds
                        ScrollBar.vertical: ScrollBar { policy: ScrollBar.AsNeeded }

                        delegate: Rectangle {
                            id: mrow
                            required property var modelData
                            required property int index
                            readonly property var prog: root.progressFor(modelData.name)
                            readonly property bool installed: root.isInstalled(modelData.name)
                            readonly property bool downloading: prog !== null
                            readonly property bool selected: root.mktRow === index
                            readonly property bool armed: root.mktArmedRemove === modelData.name
                            readonly property int mb: Math.max(1, Math.round((modelData.bytes || 0) / 1048576))
                            readonly property var tags: {
                                const a = []
                                if (modelData.video) a.push("motion")
                                if (modelData.cyber) a.push("cyber")
                                else if (modelData.light) a.push("light")
                                if ((modelData.variants || 1) > 1) a.push(modelData.variants + " plates")
                                return a
                            }

                            width: mktList.width
                            height: 78
                            radius: 10
                            color: mrow.selected ? Theme.rowSelected
                                 : (mrowHover.hovered ? Theme.rowHover : "transparent")
                            border.color: mrow.selected ? Theme.accent : Theme.glassBorder
                            border.width: 1

                            HoverHandler { id: mrowHover }
                            // hovering moves the keyboard cursor so mouse + keys agree
                            Connections {
                                target: mrowHover
                                function onHoveredChanged() {
                                    if (mrowHover.hovered && root.mktRow !== mrow.index) {
                                        root.mktRow = mrow.index
                                        root.mktArmedRemove = ""
                                    }
                                }
                            }

                            ClippingRectangle {
                                id: mthumb
                                anchors.left: parent.left
                                anchors.leftMargin: 9
                                anchors.verticalCenter: parent.verticalCenter
                                width: 116; height: 62
                                radius: 6
                                color: Theme.rowSelected
                                Image {
                                    anchors.fill: parent
                                    source: root.mktRawBase + mrow.modelData.thumb
                                    fillMode: Image.PreserveAspectCrop
                                    sourceSize: Qt.size(232, 124)
                                    asynchronous: true
                                    cache: true
                                }
                            }

                            Column {
                                anchors.left: mthumb.right
                                anchors.leftMargin: 14
                                anchors.right: mktAction.left
                                anchors.rightMargin: 14
                                anchors.verticalCenter: parent.verticalCenter
                                spacing: 5

                                Row {
                                    spacing: 8
                                    Text {
                                        anchors.verticalCenter: parent.verticalCenter
                                        text: mrow.modelData.name
                                        color: Theme.textBright
                                        font.pixelSize: 15
                                        font.weight: Font.DemiBold
                                    }
                                    Row {
                                        anchors.verticalCenter: parent.verticalCenter
                                        spacing: 3
                                        Repeater {
                                            model: mrow.modelData.accents || []
                                            delegate: Rectangle {
                                                required property var modelData
                                                width: 9; height: 9; radius: 2
                                                color: modelData
                                                border.color: Qt.rgba(0, 0, 0, 0.35); border.width: 1
                                            }
                                        }
                                    }
                                }

                                Text {
                                    width: parent.width
                                    visible: text !== ""
                                    text: mrow.modelData.tagline || ""
                                    textFormat: Text.PlainText
                                    color: Theme.textSecondary
                                    font.pixelSize: 12
                                    elide: Text.ElideRight
                                }

                                Row {
                                    spacing: 6
                                    Repeater {
                                        model: mrow.tags
                                        delegate: Rectangle {
                                            required property var modelData
                                            height: 16; width: tagT.implicitWidth + 12; radius: 4
                                            color: "transparent"
                                            border.color: Theme.glassBorder; border.width: 1
                                            Text {
                                                id: tagT; anchors.centerIn: parent
                                                text: modelData
                                                color: Theme.textMuted
                                                font.pixelSize: 10
                                                font.letterSpacing: 0.5
                                            }
                                        }
                                    }
                                }
                            }

                            // ── right-side action, state-driven ──
                            Item {
                                id: mktAction
                                anchors.right: parent.right
                                anchors.rightMargin: 12
                                anchors.verticalCenter: parent.verticalCenter
                                width: 156; height: 56

                                // downloading: progress bar + count
                                Column {
                                    anchors.centerIn: parent
                                    width: parent.width
                                    spacing: 6
                                    visible: mrow.downloading
                                    Text {
                                        anchors.horizontalCenter: parent.horizontalCenter
                                        text: mrow.prog ? ("downloading " + mrow.prog.done + "/" + mrow.prog.total) : ""
                                        color: Theme.textSecondary
                                        font.pixelSize: 11
                                    }
                                    Rectangle {
                                        width: parent.width; height: 6; radius: 3
                                        color: Theme.trackBg
                                        border.color: Theme.glassBorder; border.width: 1
                                        Rectangle {
                                            height: parent.height; radius: 3
                                            width: parent.width * (mrow.prog && mrow.prog.total > 0
                                                   ? mrow.prog.done / mrow.prog.total : 0)
                                            color: Theme.accent
                                            Behavior on width { NumberAnimation { duration: 180 } }
                                        }
                                    }
                                }

                                // armed for removal: confirm / cancel
                                Column {
                                    anchors.centerIn: parent
                                    spacing: 5
                                    visible: mrow.armed && !mrow.downloading
                                    Text {
                                        anchors.horizontalCenter: parent.horizontalCenter
                                        text: "remove theme?"
                                        color: Theme.danger
                                        font.pixelSize: 11
                                        font.weight: Font.DemiBold
                                    }
                                    Row {
                                        anchors.horizontalCenter: parent.horizontalCenter
                                        spacing: 6
                                        Rectangle {
                                            width: cfT.implicitWidth + 18; height: 26; radius: 7
                                            color: cfMa.containsMouse ? Theme.danger
                                                 : Qt.rgba(Theme.danger.r, Theme.danger.g, Theme.danger.b, 0.18)
                                            border.color: Theme.danger; border.width: 1
                                            Text { id: cfT; anchors.centerIn: parent; text: "remove"
                                                   color: Theme.textBright; font.pixelSize: 12 }
                                            MouseArea { id: cfMa; anchors.fill: parent; hoverEnabled: true
                                                cursorShape: Qt.PointingHandCursor
                                                onClicked: root.uninstallTheme(mrow.modelData.name) }
                                        }
                                        Rectangle {
                                            width: cnT.implicitWidth + 16; height: 26; radius: 7
                                            color: cnMa.containsMouse ? Theme.rowSelected : Theme.rowHover
                                            border.color: Theme.glassBorder; border.width: 1
                                            Text { id: cnT; anchors.centerIn: parent; text: "cancel"
                                                   color: Theme.textSecondary; font.pixelSize: 12 }
                                            MouseArea { id: cnMa; anchors.fill: parent; hoverEnabled: true
                                                cursorShape: Qt.PointingHandCursor
                                                onClicked: root.mktArmedRemove = "" }
                                        }
                                    }
                                }

                                // installed: apply + remove (remove hidden for the live theme)
                                Row {
                                    anchors.centerIn: parent
                                    spacing: 6
                                    visible: mrow.installed && !mrow.downloading && !mrow.armed
                                    Rectangle {
                                        anchors.verticalCenter: parent.verticalCenter
                                        width: apT.implicitWidth + 20; height: 30; radius: 8
                                        color: apMa.containsMouse ? Theme.rowSelected : Theme.rowHover
                                        border.color: Theme.glassBorder; border.width: 1
                                        Text { id: apT; anchors.centerIn: parent; text: "apply"
                                               color: Theme.textBright; font.pixelSize: 12 }
                                        MouseArea {
                                            id: apMa; anchors.fill: parent; hoverEnabled: true
                                            cursorShape: Qt.PointingHandCursor
                                            onClicked: {
                                                root.mktRow = mrow.index
                                                Quickshell.execDetached(["qs", "ipc", "call", "theme", "apply", mrow.modelData.name])
                                                root.closeMenu()
                                            }
                                        }
                                    }
                                    Rectangle {
                                        anchors.verticalCenter: parent.verticalCenter
                                        visible: !root.isActive(mrow.modelData.name)
                                        width: rmT.implicitWidth + 18; height: 30; radius: 8
                                        color: rmMa.containsMouse
                                               ? Qt.rgba(Theme.danger.r, Theme.danger.g, Theme.danger.b, 0.16) : "transparent"
                                        border.color: rmMa.containsMouse ? Theme.danger : Theme.glassBorder
                                        border.width: 1
                                        Text { id: rmT; anchors.centerIn: parent; text: "remove"
                                               color: rmMa.containsMouse ? Theme.danger : Theme.textMuted
                                               font.pixelSize: 12 }
                                        MouseArea {
                                            id: rmMa; anchors.fill: parent; hoverEnabled: true
                                            cursorShape: Qt.PointingHandCursor
                                            onClicked: { root.mktRow = mrow.index; root.mktArmedRemove = mrow.modelData.name }
                                        }
                                    }
                                }

                                // available: download button (dimmed while another install runs)
                                Rectangle {
                                    anchors.centerIn: parent
                                    visible: !mrow.installed && !mrow.downloading && !mrow.armed
                                    readonly property bool blocked: root.mktBusy !== ""
                                    width: 118; height: 34; radius: 9
                                    color: dlMa.containsMouse && !blocked ? Theme.accent : Theme.rowSelected
                                    border.color: blocked ? Theme.glassBorder : Theme.accent
                                    border.width: 1
                                    opacity: blocked ? 0.5 : 1
                                    Behavior on color { ColorAnimation { duration: 140 } }
                                    Text {
                                        anchors.centerIn: parent
                                        text: "⭳  " + mrow.mb + " MB"
                                        color: Theme.textBright
                                        font.pixelSize: 13
                                        font.weight: Font.DemiBold
                                    }
                                    MouseArea {
                                        id: dlMa; anchors.fill: parent; hoverEnabled: true
                                        cursorShape: parent.blocked ? Qt.ArrowCursor : Qt.PointingHandCursor
                                        onClicked: if (!parent.blocked) { root.mktRow = mrow.index; root.installTheme(mrow.modelData) }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
